//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactJs.RestaurantServiceOnline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurants", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Restaurants : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurant[] restaurantFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurant[] restaurantField {
            get {
                return this.restaurantFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.restaurantFieldField, value) != true)) {
                    this.restaurantFieldField = value;
                    this.RaisePropertyChanged("restaurantField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurant", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ReactJs.RestaurantServiceOnline.AddressType addressFieldField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantAppetizer[] appetizersFieldField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantEntree[] entreesFieldField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantImage imageFieldField;
        
        private string logoFieldField;
        
        private string nameFieldField;
        
        private string phoneFieldField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantReview reviewFieldField;
        
        private string summaryFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.AddressType addressField {
            get {
                return this.addressFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.addressFieldField, value) != true)) {
                    this.addressFieldField = value;
                    this.RaisePropertyChanged("addressField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantAppetizer[] appetizersField {
            get {
                return this.appetizersFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.appetizersFieldField, value) != true)) {
                    this.appetizersFieldField = value;
                    this.RaisePropertyChanged("appetizersField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantEntree[] entreesField {
            get {
                return this.entreesFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.entreesFieldField, value) != true)) {
                    this.entreesFieldField = value;
                    this.RaisePropertyChanged("entreesField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantImage imageField {
            get {
                return this.imageFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.imageFieldField, value) != true)) {
                    this.imageFieldField = value;
                    this.RaisePropertyChanged("imageField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string logoField {
            get {
                return this.logoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.logoFieldField, value) != true)) {
                    this.logoFieldField = value;
                    this.RaisePropertyChanged("logoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string phoneField {
            get {
                return this.phoneFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneFieldField, value) != true)) {
                    this.phoneFieldField = value;
                    this.RaisePropertyChanged("phoneField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantReview reviewField {
            get {
                return this.reviewFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewFieldField, value) != true)) {
                    this.reviewFieldField = value;
                    this.RaisePropertyChanged("reviewField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string summaryField {
            get {
                return this.summaryFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.summaryFieldField, value) != true)) {
                    this.summaryFieldField = value;
                    this.RaisePropertyChanged("summaryField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class AddressType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cityFieldField;
        
        private string postalCodeFieldField;
        
        private ReactJs.RestaurantServiceOnline.ProvinceType provinceFieldField;
        
        private ReactJs.RestaurantServiceOnline.AddressTypeStreet streetFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cityField {
            get {
                return this.cityFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.cityFieldField, value) != true)) {
                    this.cityFieldField = value;
                    this.RaisePropertyChanged("cityField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string postalCodeField {
            get {
                return this.postalCodeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.postalCodeFieldField, value) != true)) {
                    this.postalCodeFieldField = value;
                    this.RaisePropertyChanged("postalCodeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.ProvinceType provinceField {
            get {
                return this.provinceFieldField;
            }
            set {
                if ((this.provinceFieldField.Equals(value) != true)) {
                    this.provinceFieldField = value;
                    this.RaisePropertyChanged("provinceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.AddressTypeStreet streetField {
            get {
                return this.streetFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.streetFieldField, value) != true)) {
                    this.streetFieldField = value;
                    this.RaisePropertyChanged("streetField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantImage", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantImageHeight heightFieldField;
        
        private string nameFieldField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantImageWidth widthFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantImageHeight heightField {
            get {
                return this.heightFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.heightFieldField, value) != true)) {
                    this.heightFieldField = value;
                    this.RaisePropertyChanged("heightField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantImageWidth widthField {
            get {
                return this.widthFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.widthFieldField, value) != true)) {
                    this.widthFieldField = value;
                    this.RaisePropertyChanged("widthField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantReview", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantReview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantReviewDate dateFieldField;
        
        private int ratingFieldField;
        
        private string reviewerFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantReviewDate dateField {
            get {
                return this.dateFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.dateFieldField, value) != true)) {
                    this.dateFieldField = value;
                    this.RaisePropertyChanged("dateField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ratingField {
            get {
                return this.ratingFieldField;
            }
            set {
                if ((this.ratingFieldField.Equals(value) != true)) {
                    this.ratingFieldField = value;
                    this.RaisePropertyChanged("ratingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string reviewerField {
            get {
                return this.reviewerFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewerFieldField, value) != true)) {
                    this.reviewerFieldField = value;
                    this.RaisePropertyChanged("reviewerField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantAppetizer", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantAppetizer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string descFieldField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantAppetizerPrice[] priceFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descField {
            get {
                return this.descFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.descFieldField, value) != true)) {
                    this.descFieldField = value;
                    this.RaisePropertyChanged("descField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantAppetizerPrice[] priceField {
            get {
                return this.priceFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.priceFieldField, value) != true)) {
                    this.priceFieldField = value;
                    this.RaisePropertyChanged("priceField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantEntree", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantEntree : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string descFieldField;
        
        private ReactJs.RestaurantServiceOnline.RestaurantsRestaurantEntreePrice priceFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descField {
            get {
                return this.descFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.descFieldField, value) != true)) {
                    this.descFieldField = value;
                    this.RaisePropertyChanged("descField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ReactJs.RestaurantServiceOnline.RestaurantsRestaurantEntreePrice priceField {
            get {
                return this.priceFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.priceFieldField, value) != true)) {
                    this.priceFieldField = value;
                    this.RaisePropertyChanged("priceField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressTypeStreet", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class AddressTypeStreet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nameFieldField;
        
        private ushort numberFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ushort numberField {
            get {
                return this.numberFieldField;
            }
            set {
                if ((this.numberFieldField.Equals(value) != true)) {
                    this.numberFieldField = value;
                    this.RaisePropertyChanged("numberField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProvinceType", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum ProvinceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ontario = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Quebec = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manitoba = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alberta = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantAppetizerPrice", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantAppetizerPrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string currencyFieldField;
        
        private byte quantityFieldField;
        
        private bool quantityFieldSpecifiedField;
        
        private decimal valueFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string currencyField {
            get {
                return this.currencyFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyFieldField, value) != true)) {
                    this.currencyFieldField = value;
                    this.RaisePropertyChanged("currencyField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte quantityField {
            get {
                return this.quantityFieldField;
            }
            set {
                if ((this.quantityFieldField.Equals(value) != true)) {
                    this.quantityFieldField = value;
                    this.RaisePropertyChanged("quantityField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool quantityFieldSpecified {
            get {
                return this.quantityFieldSpecifiedField;
            }
            set {
                if ((this.quantityFieldSpecifiedField.Equals(value) != true)) {
                    this.quantityFieldSpecifiedField = value;
                    this.RaisePropertyChanged("quantityFieldSpecified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal valueField {
            get {
                return this.valueFieldField;
            }
            set {
                if ((this.valueFieldField.Equals(value) != true)) {
                    this.valueFieldField = value;
                    this.RaisePropertyChanged("valueField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantEntreePrice", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantEntreePrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string currencyFieldField;
        
        private decimal valueFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string currencyField {
            get {
                return this.currencyFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyFieldField, value) != true)) {
                    this.currencyFieldField = value;
                    this.RaisePropertyChanged("currencyField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal valueField {
            get {
                return this.valueFieldField;
            }
            set {
                if ((this.valueFieldField.Equals(value) != true)) {
                    this.valueFieldField = value;
                    this.RaisePropertyChanged("valueField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantImageHeight", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantImageHeight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string unitFieldField;
        
        private byte valueFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string unitField {
            get {
                return this.unitFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.unitFieldField, value) != true)) {
                    this.unitFieldField = value;
                    this.RaisePropertyChanged("unitField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte valueField {
            get {
                return this.valueFieldField;
            }
            set {
                if ((this.valueFieldField.Equals(value) != true)) {
                    this.valueFieldField = value;
                    this.RaisePropertyChanged("valueField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantImageWidth", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantImageWidth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string unitFieldField;
        
        private byte valueFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string unitField {
            get {
                return this.unitFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.unitFieldField, value) != true)) {
                    this.unitFieldField = value;
                    this.RaisePropertyChanged("unitField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte valueField {
            get {
                return this.valueFieldField;
            }
            set {
                if ((this.valueFieldField.Equals(value) != true)) {
                    this.valueFieldField = value;
                    this.RaisePropertyChanged("valueField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantsRestaurantReviewDate", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class RestaurantsRestaurantReviewDate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte dayFieldField;
        
        private string monthFieldField;
        
        private ushort yearFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte dayField {
            get {
                return this.dayFieldField;
            }
            set {
                if ((this.dayFieldField.Equals(value) != true)) {
                    this.dayFieldField = value;
                    this.RaisePropertyChanged("dayField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string monthField {
            get {
                return this.monthFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.monthFieldField, value) != true)) {
                    this.monthFieldField = value;
                    this.RaisePropertyChanged("monthField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ushort yearField {
            get {
                return this.yearFieldField;
            }
            set {
                if ((this.yearFieldField.Equals(value) != true)) {
                    this.yearFieldField = value;
                    this.RaisePropertyChanged("yearField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantInfo", Namespace="http://schemas.datacontract.org/2004/07/AlgonquinCollege.RestaurantReview")]
    [System.SerializableAttribute()]
    public partial class RestaurantInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReactJs.RestaurantServiceOnline.Address LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReactJs.RestaurantServiceOnline.Address Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/AlgonquinCollege.RestaurantReview")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantServiceOnline.IResturantReviewService")]
    public interface IResturantReviewService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantsFromXML", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantsFromXMLResponse")]
        ReactJs.RestaurantServiceOnline.Restaurants GetRestaurantsFromXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantsFromXML", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantsFromXMLResponse")]
        System.Threading.Tasks.Task<ReactJs.RestaurantServiceOnline.Restaurants> GetRestaurantsFromXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantNames", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantNamesResponse")]
        string[] GetRestaurantNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantNames", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantNamesResponse")]
        System.Threading.Tasks.Task<string[]> GetRestaurantNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantByName", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantByNameResponse")]
        ReactJs.RestaurantServiceOnline.RestaurantInfo GetRestaurantByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantByName", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantByNameResponse")]
        System.Threading.Tasks.Task<ReactJs.RestaurantServiceOnline.RestaurantInfo> GetRestaurantByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantsByRating", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantsByRatingResponse")]
        ReactJs.RestaurantServiceOnline.RestaurantInfo[] GetRestaurantsByRating(int rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/GetRestaurantsByRating", ReplyAction="http://tempuri.org/IResturantReviewService/GetRestaurantsByRatingResponse")]
        System.Threading.Tasks.Task<ReactJs.RestaurantServiceOnline.RestaurantInfo[]> GetRestaurantsByRatingAsync(int rating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/SaveRestaurant", ReplyAction="http://tempuri.org/IResturantReviewService/SaveRestaurantResponse")]
        bool SaveRestaurant(ReactJs.RestaurantServiceOnline.RestaurantInfo restInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantReviewService/SaveRestaurant", ReplyAction="http://tempuri.org/IResturantReviewService/SaveRestaurantResponse")]
        System.Threading.Tasks.Task<bool> SaveRestaurantAsync(ReactJs.RestaurantServiceOnline.RestaurantInfo restInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResturantReviewServiceChannel : ReactJs.RestaurantServiceOnline.IResturantReviewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResturantReviewServiceClient : System.ServiceModel.ClientBase<ReactJs.RestaurantServiceOnline.IResturantReviewService>, ReactJs.RestaurantServiceOnline.IResturantReviewService {
        
        public ResturantReviewServiceClient() {
        }
        
        public ResturantReviewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResturantReviewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResturantReviewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResturantReviewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReactJs.RestaurantServiceOnline.Restaurants GetRestaurantsFromXML() {
            return base.Channel.GetRestaurantsFromXML();
        }
        
        public System.Threading.Tasks.Task<ReactJs.RestaurantServiceOnline.Restaurants> GetRestaurantsFromXMLAsync() {
            return base.Channel.GetRestaurantsFromXMLAsync();
        }
        
        public string[] GetRestaurantNames() {
            return base.Channel.GetRestaurantNames();
        }
        
        public System.Threading.Tasks.Task<string[]> GetRestaurantNamesAsync() {
            return base.Channel.GetRestaurantNamesAsync();
        }
        
        public ReactJs.RestaurantServiceOnline.RestaurantInfo GetRestaurantByName(string name) {
            return base.Channel.GetRestaurantByName(name);
        }
        
        public System.Threading.Tasks.Task<ReactJs.RestaurantServiceOnline.RestaurantInfo> GetRestaurantByNameAsync(string name) {
            return base.Channel.GetRestaurantByNameAsync(name);
        }
        
        public ReactJs.RestaurantServiceOnline.RestaurantInfo[] GetRestaurantsByRating(int rating) {
            return base.Channel.GetRestaurantsByRating(rating);
        }
        
        public System.Threading.Tasks.Task<ReactJs.RestaurantServiceOnline.RestaurantInfo[]> GetRestaurantsByRatingAsync(int rating) {
            return base.Channel.GetRestaurantsByRatingAsync(rating);
        }
        
        public bool SaveRestaurant(ReactJs.RestaurantServiceOnline.RestaurantInfo restInfo) {
            return base.Channel.SaveRestaurant(restInfo);
        }
        
        public System.Threading.Tasks.Task<bool> SaveRestaurantAsync(ReactJs.RestaurantServiceOnline.RestaurantInfo restInfo) {
            return base.Channel.SaveRestaurantAsync(restInfo);
        }
    }
}
